### ISSUE TITLE
comments.md

### ISSUE THREAD

**Issue by yb199478** [CatLib/hexo-theme-cookbook#3]
---
title: 评论系统
---

# 评论系统

Cookbook已经内嵌了[gitment](https://github.com/imsun/gitment)评论系统，您可以通过简单的配置就能开启它。

## 申请 OAuth Application

gitment是基于github issues开发的评论系统，所以我们需要一个github的OAuth Application。

注册[OAuth application](https://github.com/settings/applications/new)后您将会获得一个`client id`和`client secret`。

`Authorization callback URL`和`Homepage URL`填写您文档项目的地址，例如:http://docs.ztgame.com/cookbook

## 配置

您还需要配置`_config.yml`文件，以便于cookbook来知道您的基本信息。

- `_config.yml`

```yaml
cookbook:
  gitment:
    enable: true
    id: cookbook
    client_id: 735737333f1390ee0558
    client_secret: ce138b79613bc12d12dbcd4addbfb0c38c2d81d2
    github_owner: yb199478
    github_repository: gitment-test
    cross_server: https://docs.ztgame.com/gitment
    per_page: 30
    maintainer:
      - giant
```

| 参数                            | 描述                 |
| -------------------------------- |:----------------------------:|
| `enable`              | gitment是否是可用的,有效值为`true`和`false`      |
| `id`                  | （可选）当前文档项目的标识符（如果您有多个文档项目共用一个github库，该值需要唯一）      |
| `client_id`           | 申请的OAuth Application的`client id`      |
| `client_secret`       | 申请的OAuth Application的`client secret`      |
| `github_owner`        | github库的账户名（如果是team则为team名）      |
| `github_repository`   | github库的库名      |
| `cross_server`        | （可选）[跨域代理服务器](#)地址      |
| `per_page`        | （可选）每页显示的评论数量      |
| `maintainer`        | （可选）维护者的github账号名（数组），拥有初始化评论系统的权限(维护者需要拥有此github库的权限)。      |

> `cross_server`办公网环境为:`https://docs.ztgame.com/gitment`

## 初始化评论

在文档页面发布后，您应该访问您的文档页面，使用您的github账户登录(并确保您是配置中的所有者)

然后单击初始化按钮，gitment会自动在您的github中建立issues，随后其他人就可以在您的文档中留下评论。

> 不要重复点击初始化按钮，这样会导致多个issues被建立。由于github存在同步延迟，请稍等片刻，或者登出您的账号重新登录。

#### 关闭指定页面的评论系统

您可以通过`comments`来关闭指定的页面评论系统。

- `source/v0/index.md`

```markdown
---
title: Hello world
comments: false
---
```

#### 为指定的页面手动给定页面标识符

默认的页面标识符是取自页面路径，当页面路径改动时将会丢失您的评论，您可以通过手动指定页面标识符来避免这个问题。

- `source/v0/index.md`

```markdown
---
title: Hello world
comments_id: hello-world.html
---
```
